import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("../lib/github", () => ({
  getFile: vi.fn(),
  putFile: vi.fn(),
  listTree: vi.fn(),
}));

import { getFile, putFile, listTree } from "../lib/github";
import {
  capture,
  getContext,
  readNote,
  todayStamp,
  validatePath,
  writeNote,
} from "../lib/brain";

const mGet = vi.mocked(getFile);
const mPut = vi.mocked(putFile);
const mList = vi.mocked(listTree);

beforeEach(() => {
  vi.resetAllMocks();
  vi.stubEnv("BRAIN_TZ", "America/Los_Angeles");
  mPut.mockResolvedValue({ commitSha: "c0" });
});

describe("validatePath", () => {
  it.each(["profile.md", "INDEX.md", "projects/beacon.md", "notes/a-b_c.md", "log/2026-07-24.md", "archive/old/x.md"])(
    "accepts %s",
    (p) => expect(() => validatePath(p)).not.toThrow()
  );
  it.each(["../etc/passwd", "src/evil.ts", "projects/x.txt", "/absolute.md", "projects/../profile.md", "random.md"])(
    "rejects %s",
    (p) => expect(() => validatePath(p)).toThrow(/Invalid brain path/)
  );
});

describe("todayStamp", () => {
  it("formats date and time in BRAIN_TZ", () => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date("2026-07-24T20:30:00Z")); // 13:30 in LA (PDT)
    expect(todayStamp()).toEqual({ date: "2026-07-24", time: "13:30" });
    vi.useRealTimers();
  });
});

describe("getContext", () => {
  it("assembles profile + index + recent logs, skipping missing days", async () => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date("2026-07-24T20:30:00Z"));
    mGet.mockImplementation(async (p: string) => {
      if (p === "profile.md") return { path: p, content: "PROFILE", sha: "s" };
      if (p === "INDEX.md") return { path: p, content: "INDEX", sha: "s" };
      if (p === "log/2026-07-24.md") return { path: p, content: "today log", sha: "s" };
      if (p === "log/2026-07-20.md") return { path: p, content: "older log", sha: "s" };
      return null;
    });
    const ctx = await getContext();
    expect(ctx).toContain("PROFILE");
    expect(ctx).toContain("INDEX");
    expect(ctx).toContain("today log");
    expect(ctx).toContain("older log");
    expect(ctx).not.toContain("2026-07-23.md"); // missing days silently skipped
    vi.useRealTimers();
  });
});

describe("getContext DST boundaries", () => {
  it("spring-forward: does not skip the day after the DST jump", async () => {
    vi.useFakeTimers();
    // 00:30 America/Los_Angeles — first hour after local midnight following the Mar 8 spring-forward
    vi.setSystemTime(new Date("2026-03-09T07:30:00Z"));
    mGet.mockImplementation(async (p: string) => {
      if (p === "profile.md") return { path: p, content: "PROFILE", sha: "s" };
      if (p === "INDEX.md") return { path: p, content: "INDEX", sha: "s" };
      return null;
    });
    await getContext();
    const logPaths = mGet.mock.calls.map((c) => c[0]).filter((p) => p.startsWith("log/"));
    expect(logPaths).toEqual([
      "log/2026-03-09.md",
      "log/2026-03-08.md",
      "log/2026-03-07.md",
      "log/2026-03-06.md",
      "log/2026-03-05.md",
      "log/2026-03-04.md",
      "log/2026-03-03.md",
    ]);
    vi.useRealTimers();
  });

  it("fall-back: does not duplicate today or drop the oldest day", async () => {
    vi.useFakeTimers();
    // 23:30 America/Los_Angeles on Nov 1 — last hour of the fall-back day
    vi.setSystemTime(new Date("2026-11-02T07:30:00Z"));
    mGet.mockImplementation(async (p: string) => {
      if (p === "profile.md") return { path: p, content: "PROFILE", sha: "s" };
      if (p === "INDEX.md") return { path: p, content: "INDEX", sha: "s" };
      return null;
    });
    await getContext();
    const logPaths = mGet.mock.calls.map((c) => c[0]).filter((p) => p.startsWith("log/"));
    expect(logPaths).toEqual([
      "log/2026-11-01.md",
      "log/2026-10-31.md",
      "log/2026-10-30.md",
      "log/2026-10-29.md",
      "log/2026-10-28.md",
      "log/2026-10-27.md",
      "log/2026-10-26.md",
    ]);
    vi.useRealTimers();
  });
});


describe("writeNote", () => {
  it("create fails when file exists", async () => {
    mGet.mockResolvedValue({ path: "notes/a.md", content: "x", sha: "s1" });
    await expect(writeNote("notes/a.md", "y", "create")).rejects.toThrow(/already exists/);
  });

  it("replace fails when file missing", async () => {
    mGet.mockResolvedValue(null);
    await expect(writeNote("notes/a.md", "y", "replace")).rejects.toThrow(/does not exist/);
  });

  it("append concatenates and regenerates index without an extra commit when unchanged", async () => {
    mGet.mockImplementation(async (p: string) =>
      p === "notes/a.md"
        ? { path: p, content: "old", sha: "s1" }
        : p === "INDEX.md"
          ? { path: p, content: "# INDEX\n\n_Auto-generated by cortex on every write — do not edit by hand._\n\n## Root\n- profile.md\n\n## notes\n- notes/a.md", sha: "s2" }
          : // every path listTree() returns must be readable, or the rich-index
            // rebuild correctly refuses to run — see "refuses to rebuild" below
            p === "profile.md"
            ? { path: p, content: "# Profile\n\nboot file", sha: "s3" }
            : null
    );
    mList.mockResolvedValue(["profile.md", "notes/a.md", "INDEX.md"]);
    const res = await writeNote("notes/a.md", "new", "append");
    expect(res).toEqual({ path: "notes/a.md", commitSha: "c0" });
    const appendCall = mPut.mock.calls.find(([p]) => p === "notes/a.md")!;
    expect(appendCall[1]).toBe("old\n\nnew");
    // INDEX content unchanged for this tree → no INDEX put
    expect(mPut.mock.calls.filter(([p]) => p === "INDEX.md")).toHaveLength(0);
  });

  it("create writes INDEX when the tree gains a file", async () => {
    mGet.mockImplementation(async (p: string) =>
      p === "INDEX.md" ? { path: p, content: "# INDEX (stale)", sha: "s2" } : null
    );
    mList.mockResolvedValue(["profile.md", "notes/new.md", "INDEX.md"]);
    await writeNote("notes/new.md", "body", "create");
    expect(mPut.mock.calls.some(([p]) => p === "INDEX.md")).toBe(true);
  });

  it("rejects invalid path before any API call", async () => {
    await expect(writeNote("evil/../x.md", "b", "create")).rejects.toThrow(/Invalid brain path/);
    expect(mGet).not.toHaveBeenCalled();
  });

  it("DATA-LOSS REGRESSION: append's merge callback re-derives from a concurrent write instead of dropping it", async () => {
    mGet.mockImplementation(async (p: string) =>
      p === "notes/a.md" ? { path: p, content: "old", sha: "s1" } : null
    );
    mList.mockResolvedValue(["profile.md", "notes/a.md"]);
    await writeNote("notes/a.md", "mine", "append");
    const appendCall = mPut.mock.calls.find(([p]) => p === "notes/a.md")!;
    const merge = appendCall[4] as (fresh: unknown) => string;
    expect(typeof merge).toBe("function");
    // Simulate: between our read and our write, someone else appended "concurrent entry".
    const result = merge({ path: "notes/a.md", content: "old\n\nconcurrent entry", sha: "s2" });
    expect(result).toContain("concurrent entry");
    expect(result).toContain("mine");
  });

  it("passes no merge callback for create/replace (replace semantics, no re-derivation)", async () => {
    mGet.mockImplementation(async (p: string) =>
      p === "notes/a.md" ? { path: p, content: "old", sha: "s1" } : null
    );
    mList.mockResolvedValue(["profile.md", "notes/a.md"]);
    await writeNote("notes/a.md", "replaced", "replace");
    const call = mPut.mock.calls.find(([p]) => p === "notes/a.md")!;
    expect(call[4]).toBeUndefined();
  });
});

describe("capture", () => {
  it("creates today's log with header when absent", async () => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date("2026-07-24T20:30:00Z"));
    mGet.mockResolvedValue(null);
    mList.mockResolvedValue(["profile.md", "INDEX.md"]);
    await capture("first thought", ["beacon"]);
    const call = mPut.mock.calls.find(([p]) => p === "log/2026-07-24.md")!;
    expect(call[1]).toBe("# Log 2026-07-24\n\n## 13:30 · beacon\n\nfirst thought\n");
    vi.useRealTimers();
  });

  it("appends an entry when today's log exists", async () => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date("2026-07-24T20:30:00Z"));
    mGet.mockImplementation(async (p: string) =>
      p === "log/2026-07-24.md"
        ? { path: p, content: "# Log 2026-07-24\n\n## 09:00\n\nearlier\n", sha: "s" }
        : null
    );
    mList.mockResolvedValue([]);
    await capture("second thought");
    const call = mPut.mock.calls.find(([p]) => p === "log/2026-07-24.md")!;
    expect(call[1]).toBe(
      "# Log 2026-07-24\n\n## 09:00\n\nearlier\n\n## 13:30\n\nsecond thought\n"
    );
    vi.useRealTimers();
  });

  it("DATA-LOSS REGRESSION: capture's merge callback re-derives from a concurrent entry instead of dropping it", async () => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date("2026-07-24T20:30:00Z"));
    mGet.mockImplementation(async (p: string) =>
      p === "log/2026-07-24.md"
        ? { path: p, content: "# Log 2026-07-24\n\n## 09:00\n\nearlier\n", sha: "s" }
        : null
    );
    mList.mockResolvedValue([]);
    await capture("second thought");
    const call = mPut.mock.calls.find(([p]) => p === "log/2026-07-24.md")!;
    const merge = call[4] as (fresh: unknown) => string;
    expect(typeof merge).toBe("function");
    const result = merge({
      path: "log/2026-07-24.md",
      content: "# Log 2026-07-24\n\n## 09:00\n\nearlier\n\n## 09:05\n\nconcurrent entry\n",
      sha: "s2",
    });
    expect(result).toContain("concurrent entry");
    expect(result).toContain("second thought");
    vi.useRealTimers();
  });
});

describe("regenerateIndex resilience (FIX C)", () => {
  it("writeNote still resolves with commitSha and carries indexWarning when index regeneration fails", async () => {
    mGet.mockResolvedValue(null);
    mList.mockRejectedValue(new Error("tree fetch boom"));
    const res = await writeNote("notes/a.md", "body", "create");
    expect(res.commitSha).toBe("c0");
    expect(res.path).toBe("notes/a.md");
    expect(res.indexWarning).toMatch(/tree fetch boom/);
  });

  it("capture still resolves with commitSha and carries indexWarning when index regeneration fails", async () => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date("2026-07-24T20:30:00Z"));
    mGet.mockResolvedValue(null);
    mList.mockRejectedValue(new Error("tree fetch boom"));
    const res = await capture("a thought");
    expect(res.commitSha).toBe("c0");
    expect(res.indexWarning).toMatch(/tree fetch boom/);
    vi.useRealTimers();
  });

  it("writeNote carries no indexWarning when regeneration succeeds", async () => {
    // `create` checks the target does not exist, THEN the rebuild reads it back.
    // Mirror that ordering rather than making one call answer both.
    let written = false;
    mGet.mockImplementation(async (p: string) => {
      if (p === "notes/a.md") {
        if (!written) { written = true; return null; }   // pre-write existence check
        return { path: p, content: "# a\n\nsome real body text", sha: "s1" };
      }
      if (p === "profile.md") return { path: p, content: "# Profile\n\nboot file", sha: "s2" };
      return null;
    });
    mList.mockResolvedValue(["profile.md", "notes/a.md"]);
    const res = await writeNote("notes/a.md", "body", "create");
    expect(res.indexWarning).toBeUndefined();
  });

});

describe("readNote", () => {
  it("throws a clear error for missing notes", async () => {
    mGet.mockResolvedValue(null);
    await expect(readNote("notes/ghost.md")).rejects.toThrow(/not found/);
  });
});

