import { execFile } from "node:child_process";
import { cpSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { promisify } from "node:util";
import { describe, expect, it } from "vitest";
import { SKIP_NAME, SKIP_PREFIX } from "../lib/corpus";

const checkout = process.cwd();
const run = promisify(execFile);
const workflowFile = ".github/workflows/ci-autofix.yml";
const policyFile = "tests/helpers/export-public-references.json";
const reference = {
  file: workflowFile,
  repository: "SampleOrg/public-task-runner",
  workflow: ".github/workflows/autofix.yml",
  ref: "0123456789abcdef0123456789abcdef01234567",
};
const inventedSentence = "The fictional bronze observatory keeps eleven paper lanterns beside its eastern storage cabinet.";
const inventedCredential = "Z9r7T2p4F6x8";
const gates = {
  path: "no real note path appears in any shipped source file",
  name: "no real note NAME appears in any shipped source file, path or not",
  prose: "no distinctive line from any real note appears in any shipped source file",
  credential: "no credential-shaped value from the brain appears in any shipped source file",
};

type GateReport = {
  numTotalTests: number;
  numPendingTests: number;
  testResults: Array<{
    assertionResults: Array<{ title: string; status: string; failureMessages: string[] }>;
  }>;
};

/** Run the unchanged gate and its real imports; only its input tree and policy are synthetic. */
async function exerciseGate(addition: string) {
  const scratch = mkdtempSync(join(tmpdir(), "cortex-export-reference-gate-"));
  const repo = join(scratch, "repo"), brain = join(scratch, "brain");
  const write = (root: string, file: string, text: string) => {
    const path = join(root, file);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, text);
  };
  try {
    // Copy helpers at invocation time so this tests the currently shipped implementation.
    cpSync(join(checkout, "lib"), join(repo, "lib"), { recursive: true });
    cpSync(join(checkout, "tests/helpers"), join(repo, "tests/helpers"), { recursive: true });
    cpSync(join(checkout, "tests/no-brain-leakage.test.ts"), join(repo, "tests/no-brain-leakage.test.ts"));
    symlinkSync(join(checkout, "node_modules"), join(repo, "node_modules"), "dir");
    write(repo, "package.json", '{"private":true,"type":"module"}\n');
    write(repo, "vitest.config.mjs", `export default {
      resolve: { alias: { "@": ${JSON.stringify(repo)} } },
      test: { environment: "node", include: ["tests/no-brain-leakage.test.ts"], maxWorkers: 1 }
    };\n`);
    write(repo, ".devcontainer/devcontainer.json", "{}\n");
    write(repo, policyFile, JSON.stringify([reference], null, 2) + "\n");
    write(repo, workflowFile, [
      `# Installed by ${reference.repository}. Do not edit this file by hand - it is`,
      `# Full description: https://github.com/${reference.repository}`,
      "name: Synthetic automation",
      "on: workflow_dispatch",
      "jobs:",
      "  repair:",
      `    uses: ${reference.repository}/${reference.workflow}@${reference.ref}`,
      addition,
      "",
    ].join("\n"));
    // Independent source files and distinct long lines satisfy every empty-corpus sentinel.
    for (let n = 0; n < 32; n++) write(repo, `docs/fixture${n}.md`, `Public fixture document ${n}.\n`);
    for (let n = 0; n < 24; n++) {
      const lines = Array.from({ length: 10 }, (_, line) =>
        `Synthetic observation ${n} entry ${line} describes an imaginary ceramic dial inside a fictional blue cabinet.`);
      write(brain, `notes/specimen${n}.md`, lines.join("\n") + "\n");
    }
    write(brain, "notes/public-task-runner.md", "# Synthetic reference collision\n");
    write(brain, "notes/fictional-cabinet-ledger.md", inventedSentence + `\nPASSWORD=${inventedCredential}\n`);
    write(brain, "tools/brain_ask.py", [
      `SKIP_PREFIX = (${SKIP_PREFIX.map(value => JSON.stringify(value)).join(", ")},)`,
      `SKIP_NAMES = (${SKIP_NAME.map(value => JSON.stringify(value)).join(", ")},)`,
      "",
    ].join("\n"));

    const reportFile = join(scratch, "report.json");
    let exitCode = 0;
    try {
      await run(process.execPath, [
        join(checkout, "node_modules/vitest/vitest.mjs"), "run",
        "tests/no-brain-leakage.test.ts", "--config", "vitest.config.mjs",
        "--reporter=json", `--outputFile=${reportFile}`,
      ], {
        cwd: repo,
        // No inherited application credentials, actual brain path, or user NODE_OPTIONS.
        env: { PATH: process.env.PATH, SystemRoot: process.env.SystemRoot, NODE_ENV: "test", CI: "1", NO_COLOR: "1", BRAIN_DIR: brain, REQUIRE_EXPORT_GATE: "1" },
        timeout: 20_000,
        maxBuffer: 2_000_000,
      });
    } catch (error) {
      const failure = error as Error & { code?: string | number; killed?: boolean };
      if (failure.code !== 1 || failure.killed) throw error;
      exitCode = 1;
    }
    const report = JSON.parse(readFileSync(reportFile, "utf8")) as GateReport;
    return { exitCode, report };
  } finally {
    // This exact directory is owned by this invocation; no repository or brain root is removed.
    rmSync(scratch, { recursive: true, force: true });
  }
}

describe("public references through the real export gate", () => {
  it.each([
    { label: "permits the three public reference forms and their policy declaration", addition: "", failures: [] },
    { label: "still rejects a private full path in the approved workflow", addition: "# note: notes/public-task-runner.md", failures: [gates.path, gates.name] },
    { label: "finds a later escaped private stem after approved reference occurrences", addition: "# carried note: \\u0070ublic-task-runner", failures: [gates.name] },
    { label: "still rejects a different private note stem in the approved workflow", addition: "# carried note: fictional-cabinet-ledger", failures: [gates.name] },
    { label: "still rejects distinctive private prose in the approved workflow", addition: `# ${inventedSentence}`, failures: [gates.prose] },
    { label: "still rejects a credential in the approved workflow", addition: `# password=${inventedCredential}`, failures: [gates.credential] },
  ])("$label", async ({ addition, failures }) => {
    const { exitCode, report } = await exerciseGate(addition);
    const assertions = report.testResults.flatMap(result => result.assertionResults);
    expect(report.numTotalTests).toBeGreaterThan(10);
    expect(report.numPendingTests).toBe(0);
    expect(assertions.some(result => result.title.includes("silently empty corpus") && result.status === "passed")).toBe(true);
    expect(assertions.filter(result => result.status === "failed").map(result => result.title).sort()).toEqual([...failures].sort());
    expect(exitCode).toBe(failures.length ? 1 : 0);
    for (const result of assertions.filter(result => result.status === "failed")) {
      expect(result.failureMessages.join("\n")).toContain(workflowFile);
    }
  }, 30_000);
});
