import { describe, expect, it } from "vitest";
import { noteNameHits, type PublicReference } from "./helpers/export-reference-policy";

const file = ".github/workflows/repair.yml";
const policyFile = "tests/helpers/export-public-references.json";
const repository = "SampleOrg/public-task-runner";
const stem = "public-task-runner";
const references: PublicReference[] = [{ file, repository, workflow: ".github/workflows/repair.yml", ref: "main" }];
const forms = [
  "# Installed by SampleOrg/public-task-runner. Do not edit this file by hand - it is",
  "# Full description: https://github.com/SampleOrg/public-task-runner",
  "    uses: SampleOrg/public-task-runner/.github/workflows/repair.yml@main",
];
const hits = (text: string, source = file, names = [stem]) => noteNameHits([[source, text]], names, references);

describe("public workflow references in the note-name gate", () => {
  it.each(forms)("recognizes only the repository span in %s", text => {
    expect(hits(text)).toEqual([]);
  });

  it("recognizes the policy's exact repository declaration, not the whole policy file", () => {
    expect(hits('    "repository": "SampleOrg/public-task-runner",', policyFile)).toEqual([]);
    expect(hits('    "explanation": "public-task-runner",', policyFile)).toEqual([{ file: policyFile, line: 1, origin: stem }]);
  });

  it.each([".github/workflows/other.yml", "docs/example.md", "tests/example.test.ts"])("does not exempt references in %s", source => {
    expect(hits(forms[0], source)).toEqual([{ file: source, line: 1, origin: stem }]);
  });

  it.each([
    "# public-task-runner",
    "# [[public-task-runner]]",
    "# notes/public-task-runner.md",
    "# https://github.com/SampleOrg/public-task-runner",
    "# Full description: https://github.com/OtherOrg/public-task-runner",
    "# Full description: https://github.com/SampleOrg/public-task-runner/private-details",
    "# Full description: https://github.com/SampleOrg/public-task-runner?private=1",
    "# Full description: https://github.com/SampleOrg/public-task-runner#private",
    "    uses: SampleOrg/public-task-runner/.github/workflows/other.yml@main",
    "    uses: SampleOrg/public-task-runner/.github/workflows/repair.yml@other",
    "    uses: SampleOrg/public-task-runner/.github/workflows/repair.yml@main # public-task-runner",
    "# Installed by SampleOrg/public-task-runner. Do not edit this file by hand - it is public-task-runner",
  ])("keeps unapproved context visible: %s", text => {
    expect(hits(text)).toEqual([{ file, line: 1, origin: stem }]);
  });

  it("does not stop at an approved first occurrence", () => {
    expect(hits(forms.join("\n") + "\n# [[public-task-runner]]")).toEqual([{ file, line: 4, origin: stem }]);
    expect(hits("# public-task-runner\n" + forms[1])).toEqual([{ file, line: 1, origin: stem }]);
  });

  it("does not approve other note names within the comment or workflow suffix", () => {
    expect(hits(forms[0], file, ["Do not edit"])).toEqual([{ file, line: 1, origin: "Do not edit" }]);
    expect(hits(forms[2], file, ["repair.yml"])).toEqual([{ file, line: 1, origin: "repair.yml" }]);
  });

  it("checks raw and decoded text independently and detects encoded extra occurrences", () => {
    expect(hits(forms[1].replaceAll("/", "\\/"))).toEqual([{ file, line: 1, origin: stem }]);
    expect(hits(forms[1] + "\n# public-task-r\\u0075nner")).toEqual([{ file, line: 2, origin: stem }]);
    expect(hits(forms[1] + "\n# public-task-r\\x75nner")).toEqual([{ file, line: 2, origin: stem }]);
  });

  it("does not turn an escaped newline into an approved standalone comment", () => {
    expect(hits("private\\n" + forms[1])).toEqual([{ file, line: 1, origin: stem }]);
  });

  it("leaves the complete source untouched for the other privacy checks", () => {
    const source: Array<[string, string]> = [[file, forms[1] + "\n# synthetic-private-topic"]];
    const original = source[0][1];
    expect(noteNameHits(source, [stem, "synthetic-private-topic"], references)).toEqual([{ file, line: 2, origin: "synthetic-private-topic" }]);
    expect(source).toEqual([[file, original]]);
  });

  it.each([
    null,
    {},
    [null],
    [{ ...references[0], file: "docs/private.md" }],
    [{ ...references[0], repository: "SampleOrg/public-task-runner/private" }],
    [{ ...references[0], workflow: "../private.md" }],
    [{ ...references[0], ref: "" }],
    [{ ...references[0], extra: "unexpected" }],
    [references[0], references[0]],
  ])("rejects invalid or ambiguous policy data %#", policy => {
    expect(() => noteNameHits([], [], policy as PublicReference[])).toThrow(/public reference policy/i);
  });
});
