/**
 * hard-corpus — adversarial edge cases for the hand-rolled tar reader and the corpus cache.
 *
 * Companion to tests/corpus.test.ts, which covers the happy path and the ustar `prefix`
 * regression. Nothing here duplicates that file.
 *
 * Every test here asserts the CORRECT behaviour and passes. Nine of them were written as
 * failing tests against the reader as it stood, and the comments on those still explain the
 * bug they caught — a pax header dropping a note, a negative size looping forever, two cold
 * requests building the corpus twice — so the reason each guard exists survives the fix.
 *
 * Every BUG test's comment says whether the input is REACHABLE (GitHub's own tarball can
 * contain it) or THEORETICAL (only a malformed/hostile archive produces it). That distinction
 * is the whole point: the tarball is generated by `git archive` on GitHub's side, so the
 * reachable set is exactly "what git emits", not "what the tar spec permits".
 */
import { describe, expect, it, beforeEach, afterEach } from "vitest";
import http from "node:http";
import type { AddressInfo } from "node:net";
import zlib from "node:zlib";
import { untar, isLive, loadCorpus, __setCache } from "../lib/corpus";

const BLOCK = 512;
const END = Buffer.alloc(BLOCK * 2); // the two zero blocks that terminate an archive

/** One 512-byte ustar header. `sizeField` overrides the encoded size for the liar tests. */
function makeHeader(o: {
  name?: string;
  prefix?: string;
  size?: number;
  sizeField?: Buffer | string;
  type?: string;
}): Buffer {
  const h = Buffer.alloc(BLOCK);
  h.write(o.name ?? "", 0, 100, "utf8");
  h.write("0000644\0", 100, 8, "ascii");
  const raw = o.sizeField ?? (o.size ?? 0).toString(8).padStart(11, "0") + "\0";
  if (Buffer.isBuffer(raw)) raw.copy(h, 124, 0, Math.min(raw.length, 12));
  else h.write(raw, 124, 12, "ascii");
  h.write(o.type ?? "0", 156, 1, "ascii");
  h.write("ustar\0" + "00", 257, 8, "ascii");
  h.write(o.prefix ?? "", 345, 155, "utf8");
  return seal(h);
}

/**
 * Write the ustar header checksum. Every real tar writer does this, and untar now rejects
 * headers that fail it — that check is what stops a mis-measured entry's payload being parsed
 * as headers. A fixture without a checksum is not a tar, so sealing here keeps these tests
 * testing the format rather than a shape no writer emits.
 */
export function seal(h: Buffer): Buffer {
  h.write(" ".repeat(8), 148, 8, "ascii");
  let sum = 0;
  for (let i = 0; i < BLOCK; i++) sum += h[i];
  h.write(sum.toString(8).padStart(6, "0") + "\0 ", 148, 8, "ascii");
  return h;
}

/** Header + payload padded to a block boundary, the way a real writer emits it. */
function entry(o: Parameters<typeof makeHeader>[0], body: string | Buffer = ""): Buffer[] {
  const data = Buffer.isBuffer(body) ? body : Buffer.from(body, "utf8");
  const pad = Buffer.alloc(Math.ceil(data.length / BLOCK) * BLOCK - data.length);
  return [makeHeader({ size: data.length, ...o }), data, pad];
}

const tar = (...parts: Array<Buffer | Buffer[]>) => Buffer.concat(parts.flat());
const files = (buf: Buffer) => new Map(untar(buf));

/** git's strbuf_append_ext_header: "<len> <key>=<value>\n", where len counts its own digits. */
function paxRecord(key: string, value: string): string {
  const rest = key.length + value.length + 3; // " ", "=", "\n"
  for (let digits = 1; digits <= 6; digits++) {
    if (String(rest + digits).length === digits) return `${rest + digits} ${key}=${value}\n`;
  }
  throw new Error("unreachable");
}

/**
 * A Buffer whose reads are budgeted, so a non-terminating parse throws instead of hanging
 * the test process. untar only ever calls toString(), indexes bytes and reads .length.
 */
function budgeted(buf: Buffer, budget: number): Buffer {
  let n = 0;
  return new Proxy(buf, {
    get(t, prop) {
      if (prop === "toString") {
        return (...args: unknown[]) => {
          if (++n > budget) throw new Error("ITERATION_BUDGET");
          return (t.toString as (...a: unknown[]) => string)(...args);
        };
      }
      const v = Reflect.get(t, prop, t);
      return typeof v === "function" ? (v as Function).bind(t) : v;
    },
  }) as Buffer;
}

// ---------------------------------------------------------------------------
// tar format cases the hand-rolled reader gets wrong
// ---------------------------------------------------------------------------

describe("untar — tar formats git actually emits", () => {
  // LATENT, not firing today — but it is one long filename away, and it fails silently.
  //
  // Verified against real `git archive --prefix=`, which is exactly what
  // GET /repos/{o}/{r}/tarball/{ref} runs. When a path will not fit in name(100) +
  // prefix(155) split at a "/", git does NOT truncate — it writes a pax extended header
  // ('x') carrying `path=<real path>` and names the data entry "<oid>.data".
  //
  // That name has no "/" in it, so `full.split("/").slice(1).join("/")` produces "" and the
  // `if (rel)` guard throws the file away. Same failure as the prefix bug: a live note
  // vanishes from the corpus and the brain answers NOT IN BRAIN for a fact it holds.
  //
  // Measured budget. GitHub's wrapper is "<owner>-<repo>-<7-char-sha>/" — verified against a
  // real tarball, it is the SHORT sha even when you request a full one — so ~26 bytes for
  // this repo. git then splits at the last "/" at index <=155, and everything after it must
  // fit in 100 BYTES. So the trigger is: a note whose BASENAME exceeds 100 bytes (non-ASCII
  // counts 2-4 bytes per character). The longest basename in the brain today is 47 bytes, so
  // this is not firing — it fires the day a generated note title runs long.
  it("OK: a pax extended header ('x') names the entry that follows it", () => {
    const wrapper = "brain-abc123/";
    const long = "a".repeat(110) + ".md";
    const full = `${wrapper}memory-2026-07/${long}`;
    const oid = "29e8e3cd1b193db4d9e5e589fd1a800df2fca220";
    const record = paxRecord("path", full);

    const buf = tar(
      // git writes this first, verbatim, on every tarball.
      entry({ name: "pax_global_header", type: "g" }, paxRecord("comment", oid)),
      entry({ name: wrapper, type: "5" }),
      entry({ name: `${wrapper}memory-2026-07/`, type: "5" }),
      entry({ name: `${oid}.paxheader`, type: "x" }, record),
      entry({ name: `${oid}.data`, type: "0" }, "long basename note\n"),
      entry({ name: `${wrapper}memory-2026-07/short.md`, type: "0" }, "short\n"),
      END
    );

    const got = files(buf);
    expect(got.get("memory-2026-07/short.md")).toBe("short\n"); // control: parser stayed aligned
    expect(got.get(`memory-2026-07/${long}`)).toBe("long basename note\n");
  });

  it("OK: a 'g' global header never renames the entries that follow it", () => {
    // git writes exactly one `pax_global_header` per archive, carrying a comment. Only a
    // per-file 'x' header may rename the next entry — treating 'g' the same way would apply
    // one path record to every remaining entry in the archive.
    const buf = tar(
      entry({ name: "pax_global_header", type: "g" }, paxRecord("comment", "deadbeef")),
      entry({ name: "brain-abc123/notes/a.md", type: "0" }, "alpha"),
      entry({ name: "brain-abc123/notes/b.md", type: "0" }, "bravo"),
      END
    );
    expect(files(buf).get("notes/a.md")).toBe("alpha");
    expect(files(buf).get("notes/b.md")).toBe("bravo");
  });

  it("OK: an 'x' header renames only the single entry that follows it", () => {
    const buf = tar(
      entry({ name: `${"b".repeat(40)}.paxheader`, type: "x" },
        paxRecord("path", "brain-abc123/notes/renamed.md")),
      entry({ name: "brain-abc123/deadbeef.data", type: "0" }, "bravo"),
      entry({ name: "brain-abc123/notes/after.md", type: "0" }, "after"),
      END
    );
    const got = files(buf);
    expect(got.get("notes/renamed.md")).toBe("bravo");
    expect(got.get("notes/after.md")).toBe("after");
    expect(got.has("deadbeef.data")).toBe(false);
  });

  // THEORETICAL for GitHub (git never writes 'L'; it uses pax). Reachable only if a tarball
  // is ever produced by GNU tar instead — e.g. a mirror, a local fixture, or a future change
  // that unpacks an archive from anywhere else.
  it("OK: a GNU longname ('L') entry is stored under its full name", () => {
    const wrapper = "brain-abc123/";
    const full = `${wrapper}notes/${"n".repeat(110)}.md`;
    const buf = tar(
      entry({ name: "././@LongLink", type: "L" }, full + "\0"),
      entry({ name: full.slice(0, 100), type: "0" }, "body"),
      END
    );
    const got = files(buf);
    expect(got.get(full.slice(wrapper.length))).toBe("body");
  });

  // THEORETICAL. base-256 kicks in past 8 GB and git uses a pax `size` record there anyway.
  // Recorded because the failure is silent and total: buf.toString("ascii") MASKS THE HIGH BIT
  // (0x80 -> 0x00), so the field reads as NUL, size becomes 0, and the payload is then parsed
  // as tar headers — everything after it in the archive is garbage.
  it("OK: a base-256 (binary) size field is decoded, not read as 0", () => {
    const body = Buffer.alloc(BLOCK, 0x41);
    const sizeField = Buffer.alloc(12);
    sizeField[0] = 0x80; // binary marker
    sizeField.writeUInt32BE(body.length, 8);
    const buf = tar(
      [makeHeader({ name: "brain-abc123/notes/big.md", sizeField }), body],
      entry({ name: "brain-abc123/notes/after.md" }, "still here"),
      END
    );
    const got = files(buf);
    expect(got.get("notes/big.md")).toBe(body.toString("utf8"));
    expect(got.get("notes/after.md")).toBe("still here");
  });

  it("OK: a size field padded with spaces instead of NUL still parses", () => {
    // Some writers use "         12 " rather than a NUL terminator. .trim() covers it.
    const buf = tar(
      entry({ name: "brain-abc123/notes/a.md", sizeField: "         12 " }, "0123456789"),
      entry({ name: "brain-abc123/notes/b.md" }, "next"),
      END
    );
    const got = files(buf);
    expect(got.get("notes/a.md")).toBe("0123456789");
    expect(got.get("notes/b.md")).toBe("next");
  });

  it("OK: directories are skipped, but a symlinked NOTE fails loud instead of vanishing", () => {
    // A symlinked note carries no payload, so it used to disappear from the corpus with no
    // signal — the brain would answer NOT IN BRAIN for a note that plainly exists. Silence is
    // the failure mode this reader has already had twice, so a link the operator can fix is an error.
    const dirs = tar(entry({ name: "brain-abc123/notes/", type: "5" }),
                     entry({ name: "brain-abc123/notes/real.md", type: "0" }, "real"), END);
    expect(untar(dirs)).toEqual([["notes/real.md", "real"]]);

    for (const type of ["2", "1"]) {
      const buf = tar(entry({ name: "brain-abc123/notes/link.md", type }), END);
      expect(() => untar(buf, isLive)).toThrow(/link, not a file/);
    }
  });
});

// ---------------------------------------------------------------------------
// malformed / hostile input
// ---------------------------------------------------------------------------

describe("untar — malformed input", () => {
  // THEORETICAL over HTTPS to GitHub: a truncated download fails in gunzip long before untar
  // sees it. Recorded because the failure mode is the worst kind for this system — a note is
  // served SHORT, with no error, and the reader answers confidently from half a note.
  it("OK: a size larger than the remaining buffer is refused, not silently truncated", () => {
    const header = makeHeader({ name: "brain-abc123/notes/a.md", size: 4096 });
    const buf = tar([header, Buffer.from("only 512 bytes of this file survived".padEnd(BLOCK, " "))]);
    // Refuses the whole archive: emitting a short note as though complete is the one thing
    // this reader must never do.
    expect(() => untar(buf)).toThrow(/declares 4096 bytes/);
  });

  // THEORETICAL. `parseInt(field, 8)` accepts a leading "-": a size of -512 makes
  // `off += Math.ceil(size / 512) * 512` walk BACKWARDS onto the same header, forever. A big
  // negative walks off past zero, where buf.toString clamps a negative start to 0 and returns
  // "", so `off` crawls back up 512 bytes at a time and re-reads the same poisoned header.
  // untar is synchronous, so this pins the function's event loop until the platform timeout.
  it("OK: a negative size field is rejected instead of looping forever", () => {
    const good = tar(entry({ name: "brain-abc123/notes/a.md" }, "alpha"), END);
    expect(() => untar(budgeted(good, 50_000))).not.toThrow(); // control: budget is generous

    const evil = tar(
      [makeHeader({ name: "brain-abc123/notes/a.md", sizeField: "-0000001000" })],
      Buffer.alloc(BLOCK),
      END
    );
    // Rejected outright, so `off` never walks backwards and the loop always terminates.
    expect(() => untar(budgeted(evil, 50_000))).toThrow(/not octal|declares size/);
  });

  // THEORETICAL. The `if (!name)` branch skips the size field, so a nameless header's PAYLOAD
  // is reinterpreted as tar headers. That is an entry-injection primitive: file bytes become
  // corpus entries. It needs a malformed archive to trigger, but the consequence is the one
  // thing this system must never do — serve text that is not what the repo holds.
  it("OK: a nameless header is refused, so its payload cannot be parsed as headers", () => {
    const phantom = tar(entry({ name: "brain-abc123/notes/injected.md" }, "not in the repo"));
    const buf = tar([makeHeader({ name: "", size: phantom.length })], phantom, END);
    expect(() => untar(buf)).toThrow(/no path below the archive root/);
  });

  // THEORETICAL. Nothing stops at the two zero blocks; the reader scans to the end of the
  // buffer, so anything appended to a valid archive is ingested as corpus.
  it("OK: entries after the end-of-archive marker are not ingested", () => {
    const buf = tar(
      entry({ name: "brain-abc123/notes/real.md" }, "real"),
      END,
      entry({ name: "brain-abc123/notes/appended.md" }, "appended after EOF"),
      END
    );
    const got = files(buf);
    expect(got.get("notes/real.md")).toBe("real");
    expect(got.has("notes/appended.md")).toBe(false);
  });

  it("OK: a header truncated mid-block is ignored rather than throwing", () => {
    const buf = tar(entry({ name: "brain-abc123/notes/a.md" }, "alpha"), [Buffer.alloc(200)]);
    expect(untar(buf)).toEqual([["notes/a.md", "alpha"]]);
  });

  it("OK: a non-octal size field is refused rather than coerced to 0", () => {
    // The old reader did `parseInt(field, 8) || 0`, so "99999999999" became size 0 and the
    // entry was emitted EMPTY — a note served as blank rather than as missing or as an error.
    const buf = tar([makeHeader({ name: "brain-abc123/notes/a.md", sizeField: "99999999999" })], END);
    expect(() => untar(buf)).toThrow(/not octal/);
  });
});

// ---------------------------------------------------------------------------
// encoding
// ---------------------------------------------------------------------------

describe("untar — encoding", () => {
  it("OK: multi-byte UTF-8 bodies and filenames round-trip exactly", () => {
    // The size field is a BYTE count and the slice is exact, so there is no boundary to split.
    const body = "café — naïve — 🧠 ünïcödé\nsecond line\n";
    const buf = tar(entry({ name: "brain-abc123/notes/café-🧠.md" }, body), END);
    expect(files(buf).get("notes/café-🧠.md")).toBe(body);
  });

  it("OK: a name that fills the whole 100-byte field with no NUL terminator is read intact", () => {
    const name = "brain-abc123/notes/" + "n".repeat(100 - 19 - 3) + ".md";
    expect(Buffer.byteLength(name)).toBe(100);
    const buf = tar(entry({ name }, "body"), END);
    expect(files(buf).get(name.slice("brain-abc123/".length))).toBe("body");
  });

  it("OK: a NUL byte inside a file body survives (only the name fields are NUL-trimmed)", () => {
    const body = "before\0after";
    const buf = tar(entry({ name: "brain-abc123/notes/nul.md" }, body), END);
    expect(files(buf).get("notes/nul.md")).toBe(body);
  });

  it("OK: untar materialises every entry as a string before isLive can filter it", () => {
    // Not a bug, a cost: a binary blob anywhere in the repo (tools/, .github/, an image) is
    // fully UTF-8 decoded into a JS string and only then discarded by loadCorpus's filter.
    // There is no cap anywhere on the decoded total.
    const blob = Buffer.alloc(64 * 1024, 0xff);
    const buf = tar(entry({ name: "brain-abc123/tools/blob.bin" }, blob), END);
    expect(files(buf).get("tools/blob.bin")!.length).toBeGreaterThan(0);
  });
});

// ---------------------------------------------------------------------------
// path traversal — where does `rel` actually end up?
// ---------------------------------------------------------------------------

describe("untar — path traversal", () => {
  it("OK: a traversing entry name is inert — the path is only ever a Map key", () => {
    // git refuses to store ".." or a leading "/" in a tree, so this cannot come out of the
    // GitHub tarball at all. And nothing in lib/ touches the filesystem — the corpus path is
    // a Map key, a line in the prompt, and a lookup in checkCitation. Nothing resolves it.
    // Worth pinning anyway so a future "write the corpus to disk" change is forced to notice.
    const buf = tar(
      entry({ name: "brain-abc123/../../../etc/passwd.md" }, "root:x:0:0"),
      entry({ name: "/etc/shadow.md" }, "shadow"),
      END
    );
    const got = files(buf);
    expect(got.get("../../../etc/passwd.md")).toBe("root:x:0:0"); // survives as a key, nothing more
    expect(got.get("etc/shadow.md")).toBe("shadow"); // absolute path: slice(1) eats the empty head
    expect(isLive("../../../etc/passwd.md")).toBe(true); // and it does reach the corpus
    expect(isLive("../../../etc/passwd")).toBe(false); // ...only if it ends in .md
  });
});

// ---------------------------------------------------------------------------
// isLive
// ---------------------------------------------------------------------------

describe("isLive — bypasses", () => {
  it("OK: exclusion is a literal prefix match — these shapes bypass it, none are reachable", () => {
    // Documented, not fixed: git cannot emit "./" or ".." path components, and the corpus
    // paths come from nowhere else. The list matters if untar ever normalises paths, or if a
    // second producer (a local clone walker) is ever added.
    expect(isLive("tools//foo.md")).toBe(false); // still caught — the prefix is intact
    expect(isLive("./tools/foo.md")).toBe(true); // BYPASS
    expect(isLive("notes/../tools/secret.md")).toBe(true); // BYPASS
    expect(isLive("TOOLS/foo.md")).toBe(true); // BYPASS — comparison is case-sensitive
    expect(isLive("Archive/old.md")).toBe(true); // BYPASS
  });

  it("OK: the .md test is case-INsensitive, so a note named X.MD is in the corpus", () => {
    // Was the only bypass on this list the operator could trigger by hand, and it failed toward
    // omission: the note exists and the brain answered NOT IN BRAIN for it. brain_ask.py's
    // live_files() carries the same case-insensitive test, or the two corpora drift.
    expect(isLive("notes/Setup.MD")).toBe(true);
    expect(isLive("notes/Setup.Md")).toBe(true);
    expect(isLive("notes/setup.markdown")).toBe(false);
  });

  it("OK: exclusions key off the directory, not a substring", () => {
    expect(isLive("archive.md")).toBe(true); // a note named archive, not the archive dir
    expect(isLive("archive")).toBe(false); // not markdown
    expect(isLive("notes/toolsy/x.md")).toBe(true);
    expect(isLive("brain-index.md")).toBe(false);
    expect(isLive("deep/nested/brain-index.md")).toBe(false); // SKIP_NAME is a basename test
  });
});

// ---------------------------------------------------------------------------
// loadCorpus — cache behaviour
// ---------------------------------------------------------------------------

describe("loadCorpus — cache under stress", () => {
  const origFetch = globalThis.fetch;

  const gzTar = (map: Record<string, string>) =>
    zlib.gzipSync(
      tar(...Object.entries(map).map(([n, b]) => entry({ name: `brain-abc123/${n}` }, b)), END)
    );

  beforeEach(() => {
    __setCache(null);
    process.env.BRAIN_REPO = "acme/brain";
    process.env.GITHUB_TOKEN = "t";
  });
  afterEach(() => {
    globalThis.fetch = origFetch;
    __setCache(null);
  });

  // REACHABLE. Two MCP requests landing on the same cold Vercel instance is the normal case,
  // not an edge case. Both miss, both fetch, both gunzip and both build a full corpus.
  it("OK: two concurrent cold calls share one fetch and one build", async () => {
    const tarball = gzTar({ "profile.md": "operator" });
    let tarballCalls = 0;
    globalThis.fetch = (async (url: string) => {
      if (String(url).includes("/commits/")) {
        return new Response(JSON.stringify({ sha: "sha1" }), { status: 200 });
      }
      tarballCalls++;
      await new Promise((r) => setTimeout(r, 20)); // the race window
      return new Response(new Uint8Array(tarball), { status: 200 });
    }) as typeof fetch;

    const [a, b] = await Promise.all([loadCorpus(), loadCorpus()]);
    expect(tarballCalls).toBe(1); // an in-flight promise should be shared
    expect(a).toBe(b); // and both callers should see the same object
  });

  it("OK: a failed tarball fetch never clobbers a good cache and never exposes half a corpus", async () => {
    const tarball = gzTar({ "profile.md": "operator", "projects/beacon.md": "dark" });
    let head = "sha1";
    let tarballCalls = 0;
    globalThis.fetch = (async (url: string) => {
      if (String(url).includes("/commits/")) {
        return new Response(JSON.stringify({ sha: head }), { status: 200 });
      }
      tarballCalls++;
      return head === "sha1"
        ? new Response(new Uint8Array(tarball), { status: 200 })
        : new Response("nope", { status: 404 });
    }) as typeof fetch;

    const warm = await loadCorpus();
    expect(warm.files.size).toBe(2);

    head = "sha2"; // a new commit whose tarball is unavailable
    await expect(loadCorpus()).rejects.toThrow(/HTTP 404/);

    head = "sha1"; // the old corpus is still intact and still served without a refetch
    const before = tarballCalls;
    expect(await loadCorpus()).toBe(warm);
    expect(tarballCalls).toBe(before);
  });

  // REACHABLE. GitHub 5xx and secondary rate limits are ordinary events. Today the head call
  // is a hard dependency on EVERY request: a complete, verified corpus sits in memory and the
  // brain still answers with an exception. Serving the cached corpus is not "half a brain" —
  // it is a whole one, and every answer already carries the commit it was proven against, so
  // staleness stays visible. This is a policy call, not a correctness defect; recorded here
  // because the current policy is unstated and maximally brittle.
  it("BUG(policy): a transient head-sha failure takes the brain down despite a warm cache", async () => {
    const tarball = gzTar({ "profile.md": "operator" });
    let headOk = true;
    globalThis.fetch = (async (url: string) => {
      if (String(url).includes("/commits/")) {
        return headOk
          ? new Response(JSON.stringify({ sha: "sha1" }), { status: 200 })
          : new Response("upstream", { status: 502 });
      }
      return new Response(new Uint8Array(tarball), { status: 200 });
    }) as typeof fetch;

    const warm = await loadCorpus();
    headOk = false;
    await expect(loadCorpus()).resolves.toBe(warm);
  });
});

// ---------------------------------------------------------------------------
// the credential assumption the tarball path is built on
// ---------------------------------------------------------------------------

describe("gh() — Authorization on the tarball redirect", () => {
  /** Two servers on different ports = different origins. */
  async function listen(handler: http.RequestListener): Promise<{ url: string; close: () => Promise<void> }> {
    const s = http.createServer(handler);
    await new Promise<void>((r) => s.listen(0, "127.0.0.1", r));
    const port = (s.address() as AddressInfo).port;
    return {
      url: `http://127.0.0.1:${port}`,
      close: () => new Promise<void>((r) => s.close(() => r())),
    };
  }

  it("OK: fetch strips Authorization on a cross-origin redirect, and keeps it same-origin", async () => {
    // corpus.ts's header comment stakes the whole two-request design on this: the API 302s to
    // codeload with a pre-signed URL, and the token must not ride along to the second host.
    // gh() passes no `redirect` option, so this platform behaviour IS the protection.
    let seen: string | undefined | null = "unset";
    const dest = await listen((req, res) => {
      seen = req.headers.authorization ?? null;
      res.end("ok");
    });
    const hop = await listen((req, res) => {
      if (req.url === "/same") {
        seen = req.headers.authorization ?? null;
        res.end("ok");
        return;
      }
      res.writeHead(302, { Location: req.url === "/cross" ? `${dest.url}/x` : "/same" });
      res.end();
    });
    try {
      await fetch(`${hop.url}/cross`, { headers: { Authorization: "Bearer SECRET" } });
      expect(seen).toBe(null); // codeload never sees the token

      await fetch(`${hop.url}/inner`, { headers: { Authorization: "Bearer SECRET" } });
      expect(seen).toBe("Bearer SECRET"); // and a same-origin hop still authenticates
    } finally {
      await hop.close();
      await dest.close();
    }
  });
});
