import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("../lib/corpus", () => ({ loadCorpus: vi.fn() }));

import { loadCorpus } from "../lib/corpus";
import { health } from "../lib/health";

const mLoad = vi.mocked(loadCorpus);

function corpus(files: Array<[string, string]>) {
  return {
    sha: "e".repeat(40),
    bytes: files.reduce((a, [, t]) => a + t.length, 0),
    files: new Map(files),
  } as unknown as Awaited<ReturnType<typeof loadCorpus>>;
}

/** The shape that caused the defect: a page that documents killing a tool names it constantly. */
const CHANGELOG = `# cortex

## DEFECT — brain_recall answers from a superseded page

SUPERSEDED 2026-07-30 — brain_recall was deleted in Stage 5.

The brain_recall defect: brain_recall ranked brain-index.md, and brain_recall
opened the wrong note. recall.py and build_index had the same flaw.

## Stage 5 rough edges

The shims still point at recall.py and build_index.
`;

/** The genuinely dangerous shape: fewer mentions, none marked, all asserted as current. */
const BELIEVER = `# Second brain

The brain has a deterministic retrieval layer. Retrieval is recall.py.

## Index

The index is generated by build_index from the notes.
`;

beforeEach(() => vi.resetAllMocks());

describe("retiredRefs ranking", () => {
  it("ranks the note that believes in the dead tools above the changelog that killed them", async () => {
    mLoad.mockResolvedValue(
      corpus([
        ["projects/cortex.md", CHANGELOG],
        ["notes/second-brain.md", BELIEVER],
      ]),
    );
    const h = await health();

    // The regression: by raw mention count the changelog wins easily.
    const rawCounts = [...(await loadCorpus()).files].map(([p, t]) => ({
      path: p,
      raw: ["brain_recall", "brain_search", "brain-index.md", "build_index", "recall.py"].reduce(
        (a, term) => a + t.split(term).length - 1,
        0,
      ),
    }));
    expect(rawCounts.find((r) => r.path === "projects/cortex.md")!.raw).toBeGreaterThan(
      rawCounts.find((r) => r.path === "notes/second-brain.md")!.raw,
    );

    // What the panel must actually say.
    expect(h.retiredRefs[0].path).toBe("notes/second-brain.md");
    expect(h.retiredRefs[0].marked).toBe(0);
  });

  it("counts an already-marked passage as handled, not as a problem", async () => {
    mLoad.mockResolvedValue(corpus([["projects/cortex.md", CHANGELOG]]));
    const [ref] = (await health()).retiredRefs;

    expect(ref.marked).toBeGreaterThan(0);
    // The block under the SUPERSEDED heading must never appear as unmarked.
    expect(ref.lines).not.toContain(6);
  });

  it("excludes dated log entries, which were true on their date", async () => {
    mLoad.mockResolvedValue(
      corpus([
        ["log/2026-07-26.md", "# Log\n\nbrain_recall is live in production. brain_search works.\n"],
        ["notes/evergreen.md", "# Note\n\nrecall.py is how retrieval works.\n"],
      ]),
    );
    const h = await health();

    expect(h.retiredRefs.map((r) => r.path)).toEqual(["notes/evergreen.md"]);
  });

  it("does not exclude a dated-looking name that is not a whole filename", async () => {
    mLoad.mockResolvedValue(
      corpus([["projects/plan-2026-07-26-rollout.md", "# Plan\n\nUse recall.py.\n"]]),
    );
    expect((await health()).retiredRefs).toHaveLength(1);
  });

  it("reports the lines to look at, and every reported line holds a retired term", async () => {
    mLoad.mockResolvedValue(corpus([["notes/second-brain.md", BELIEVER]]));
    const [ref] = (await health()).retiredRefs;
    const lines = BELIEVER.split("\n");

    expect(ref.lines.length).toBe(ref.unmarked);
    for (const l of ref.lines) {
      const window = lines.slice(l - 1, l + 2).join("\n");
      expect(window).toMatch(/brain_recall|brain_search|brain-index\.md|build_index|recall\.py/);
    }
  });

  it("dedupes terms per note rather than listing one entry per mention", async () => {
    mLoad.mockResolvedValue(corpus([["notes/n.md", "# N\n\nrecall.py, recall.py, recall.py.\n"]]));
    expect((await health()).retiredRefs[0].terms).toEqual(["recall.py"]);
  });

  it("says nothing when every mention is already marked", async () => {
    mLoad.mockResolvedValue(
      corpus([["notes/done.md", "# Done — SUPERSEDED 2026-07-30\n\nrecall.py ranked the index.\n"]]),
    );
    expect((await health()).retiredRefs).toHaveLength(0);
  });
});
