import { beforeEach, describe, expect, it, vi } from "vitest";
import { corpus } from "./helpers/health-corpus";

vi.mock("../lib/corpus", () => ({ loadCorpus: vi.fn() }));

import { loadCorpus } from "../lib/corpus";
import { health } from "../lib/health";

const mLoad = vi.mocked(loadCorpus);


/** The shape that caused the defect: a page that documents killing a tool names it constantly. */
const CHANGELOG = `# cortex

## DEFECT — brain_recall answers from a superseded page

SUPERSEDED 2026-07-30 — brain_recall was deleted in Stage 5.

The brain_recall defect: brain_recall ranked brain-index.md, and brain_recall
opened the wrong note. recall.py and build_index had the same flaw.

## Stage 5 rough edges

The shims still point at recall.py and build_index.
`;

/** The genuinely dangerous shape: fewer mentions, none marked, all asserted as current. */
const BELIEVER = `# Second brain

The brain has a deterministic retrieval layer. Retrieval is recall.py.

## Index

The index is generated by build_index from the notes.
`;

beforeEach(() => vi.resetAllMocks());

describe("retiredRefs ranking", () => {
  it("ranks the note that believes in the dead tools above the changelog that killed them", async () => {
    mLoad.mockResolvedValue(
      corpus([
        ["projects/atlas.md", CHANGELOG],
        ["notes/memory-design.md", BELIEVER],
      ]),
    );
    const h = await health();

    // The regression: by raw mention count the changelog wins easily.
    const rawCounts = [...(await loadCorpus()).files].map(([p, t]) => ({
      path: p,
      raw: ["brain_recall", "brain_search", "brain-index.md", "build_index", "recall.py"].reduce(
        (a, term) => a + t.split(term).length - 1,
        0,
      ),
    }));
    expect(rawCounts.find((r) => r.path === "projects/atlas.md")!.raw).toBeGreaterThan(
      rawCounts.find((r) => r.path === "notes/memory-design.md")!.raw,
    );

    // What the panel must actually say.
    expect(h.retiredRefs[0].path).toBe("notes/memory-design.md");
    expect(h.retiredRefs[0].marked).toBe(0);
  });

  it("counts an already-marked passage as handled, not as a problem", async () => {
    mLoad.mockResolvedValue(corpus([["projects/atlas.md", CHANGELOG]]));
    const [ref] = (await health()).retiredRefs;

    expect(ref.marked).toBeGreaterThan(0);
    // The block under the SUPERSEDED heading must never appear as unmarked.
    expect(ref.lines).not.toContain(6);
  });

  it("excludes dated log entries, which were true on their date", async () => {
    mLoad.mockResolvedValue(
      corpus([
        ["log/2026-07-26.md", "# Log\n\nbrain_recall is live in production. brain_search works.\n"],
        ["notes/evergreen.md", "# Note\n\nrecall.py is how retrieval works.\n"],
      ]),
    );
    const h = await health();

    expect(h.retiredRefs.map((r) => r.path)).toEqual(["notes/evergreen.md"]);
  });

  it("does not exclude a dated-looking name that is not a whole filename", async () => {
    mLoad.mockResolvedValue(
      corpus([["projects/plan-2026-07-26-rollout.md", "# Plan\n\nUse recall.py.\n"]]),
    );
    expect((await health()).retiredRefs).toHaveLength(1);
  });

  it("reports the lines to look at, and every reported line holds a retired term", async () => {
    mLoad.mockResolvedValue(corpus([["notes/memory-design.md", BELIEVER]]));
    const [ref] = (await health()).retiredRefs;
    const lines = BELIEVER.split("\n");

    expect(ref.lines.length).toBe(ref.unmarked);
    for (const l of ref.lines) {
      const window = lines.slice(l - 1, l + 2).join("\n");
      expect(window).toMatch(/brain_recall|brain_search|brain-index\.md|build_index|recall\.py/);
    }
  });

  it("dedupes terms per note rather than listing one entry per mention", async () => {
    mLoad.mockResolvedValue(corpus([["notes/n.md", "# N\n\nrecall.py, recall.py, recall.py.\n"]]));
    expect((await health()).retiredRefs[0].terms).toEqual(["recall.py"]);
  });

  it("says nothing when every mention is already marked", async () => {
    mLoad.mockResolvedValue(
      corpus([["notes/done.md", "# Done — SUPERSEDED 2026-07-30\n\nrecall.py ranked the index.\n"]]),
    );
    expect((await health()).retiredRefs).toHaveLength(0);
  });
});

describe("triage tuning", () => {
  it("does not alert on the shapes that were never secrets", async () => {
    const { plausibleSecret } = await import("../lib/health");
    // The four false positives the queue actually carried, by shape:
    expect(plausibleSecret("sudo is ENABLED via sudoers (`operator ALL=(ALL) NOPASSWD: ALL`)")).toBe(false);
    expect(plausibleSecret("Fix: `~/.zshrc` now has `export GITHUB_PERSONAL_ACCESS_TOKEN=<your-pat-here>`")).toBe(false);
    expect(plausibleSecret("override inline: `GITHUB_TOKEN=ghp_exampl npx tsx ...`")).toBe(false);
    expect(plausibleSecret("MY_TOKEN=${SOME_OTHER_VAR}")).toBe(false);
    // And the shape that IS worth a critical alert: secret-ish name, long opaque value.
    expect(plausibleSecret("API_SECRET=k9f2mQ81xPzL04vWyTr7NnB3")).toBe(true);
  });

  it("treats command and variable substitution as indirection, not a secret", async () => {
    const { plausibleSecret } = await import("../lib/health");
    expect(plausibleSecret('export GITHUB_PERSONAL_ACCESS_TOKEN="$(security find-generic-password -s github-pat -w)"')).toBe(false);
    expect(plausibleSecret('GITHUB_TOKEN="${VAULT_GITHUB_TOKEN}" gh api …')).toBe(false);
  });

  it("alerts on a colon / JSON-form secret exactly as on its = twin — redact classifies both", async () => {
    const { plausibleSecret } = await import("../lib/health");
    // redact() keys kind=key=value on `["']?\s*[:=]`, so the colon form is flagged AND classified
    // the same as `=`; the gate must agree or a JSON/YAML credential is masked yet never surfaced.
    expect(plausibleSecret("api_key: 3f9a8b7c6d5e4f0a1b2c3d4e")).toBe(true);
    expect(plausibleSecret('"api_key": "3f9a8b7c6d5e4f0a1b2c3d4e"')).toBe(true);
    // The same length and placeholder gates still apply on the colon side.
    expect(plausibleSecret("api_key: <your-key-here>")).toBe(false);
    expect(plausibleSecret("api_key: short")).toBe(false);
  });

  it("a benign leading word: no longer masks a real KEY=secret later on the line", async () => {
    const { plausibleSecret } = await import("../lib/health");
    // A single first-match exec stopped at "Fix:" and returned before reaching the credential.
    expect(plausibleSecret("Fix: rotate the GITHUB_TOKEN=ghp_9f2mQ81xPzL04vWyTr7NnB3aa now")).toBe(true);
  });
});

describe("colon / JSON-form credentials reach the crit queue, not just the = form", () => {
  it("a `key: <opaque>` line produces a crit Credential-shaped item, like its = twin", async () => {
    mLoad.mockResolvedValue(
      corpus([["notes/creds.md", "# Creds\n\napi_key: 3f9a8b7c6d5e4f0a1b2c3d4e\n"]]),
    );
    const h = await health();
    expect(h.secrets).toContainEqual({ path: "notes/creds.md", line: 3, kind: "key=value" });
    expect(
      h.triage.some((t) => t.title === "Credential-shaped line" && t.loc === "notes/creds.md:3"),
    ).toBe(true);
  });
});
