import type { BrainFile } from "./github";
import { getFile, listTree, putFile } from "./github";
import { isLive } from "./corpus";
import { redact } from "./redact";

// Write policy: what a caller may create or overwrite. Deliberately narrow.
const PATH_RE =
  /^(profile\.md|INDEX\.md|(projects|notes|log)\/[A-Za-z0-9._-]+\.md|archive\/[A-Za-z0-9._/-]+\.md)$/;


export function validatePath(path: string): void {
  if (!PATH_RE.test(path) || path.includes("..")) {
    throw new Error(
      `Invalid brain path: ${path}. Allowed: profile.md, INDEX.md, projects/*.md, notes/*.md, log/*.md, archive/**.md`
    );
  }
}

export function todayStamp(): { date: string; time: string } {
  const tz = process.env.BRAIN_TZ ?? "UTC";
  const now = new Date();
  const date = new Intl.DateTimeFormat("en-CA", {
    timeZone: tz,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(now);
  const time = new Intl.DateTimeFormat("en-GB", {
    timeZone: tz,
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  }).format(now);
  return { date, time };
}

function lastNDates(n: number): string[] {
  const tz = process.env.BRAIN_TZ ?? "UTC";
  const fmt = new Intl.DateTimeFormat("en-CA", {
    timeZone: tz,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  });
  const [y, m, d] = fmt.format(new Date()).split("-").map(Number);
  const out: string[] = [];
  for (let i = 0; i < n; i++) {
    const dt = new Date(Date.UTC(y, m - 1, d - i));
    out.push(
      `${dt.getUTCFullYear()}-${String(dt.getUTCMonth() + 1).padStart(2, "0")}-${String(dt.getUTCDate()).padStart(2, "0")}`
    );
  }
  return out;
}

export async function getContext(): Promise<string> {
  const days = lastNDates(7);
  const [profile, index, ...logs] = await Promise.all([
    getFile("profile.md"),
    getFile("INDEX.md"),
    ...days.map((d) => getFile(`log/${d}.md`)),
  ]);
  const parts: string[] = [];
  parts.push("# PROFILE\n\n" + (profile?.content ?? "(profile.md missing)"));
  parts.push("# INDEX\n\n" + (index?.content ?? "(INDEX.md missing)"));
  const found = logs.filter((l): l is NonNullable<typeof l> => l !== null);
  if (found.length > 0) {
    parts.push(
      "# RECENT LOG (last 7 days)\n\n" +
        found.map((l) => `--- ${l.path} ---\n${l.content}`).join("\n\n")
    );
  }
  return parts.join("\n\n");
}


const READ_CHUNK_SIZE = 8;


export async function readNote(path: string): Promise<string> {
  validatePath(path);
  const f = await getFile(path);
  if (!f) throw new Error(`Note not found: ${path}`);
  // Redaction is announced, not silent: a reader who sees `<redacted>` and no explanation
  // cannot tell whether the note literally says that. Announcing it also tells the operator a
  // credential is sitting in his notes, which is the thing he actually needs to know.
  const safe = redact(f.content);
  return safe === f.content
    ? safe
    : `${safe}\n\n---\n(NOTE: credential-shaped values in this file were redacted on the way out. Read the file directly if you need the real value.)`;
}

function joinAppend(existing: string | undefined, addition: string, whenMissing: string): string {
  return existing ? existing.replace(/\s+$/, "") + "\n\n" + addition : whenMissing;
}

async function regenerateBareIndex(): Promise<void> {
  const paths = (await listTree()).filter((p) => p !== "INDEX.md");
  const groups = new Map<string, string[]>();
  for (const p of paths) {
    const dir = p.includes("/") ? p.split("/")[0] : "Root";
    if (!groups.has(dir)) groups.set(dir, []);
    groups.get(dir)!.push(p);
  }
  const order = ["Root", "projects", "notes", "log", "archive"];
  const body = order
    .filter((d) => groups.has(d))
    .map((d) => `## ${d}\n` + groups.get(d)!.sort().map((p) => `- ${p}`).join("\n"))
    .join("\n\n");
  const content = `# INDEX\n\n_Auto-generated by cortex on every write — do not edit by hand._\n\n${body}`;
  const existing = await getFile("INDEX.md");
  if (existing?.content === content) return; // unchanged tree → no commit churn
  await putFile("INDEX.md", content, "brain: regenerate index", existing?.sha);
}


// The bare INDEX.md path listing is the only generated catalogue left. It exists for
// brain_context, which ships it as a map of what the brain contains; nothing ranks it.
// Reported through the indexWarning channel rather than failing the write — the note is
// already committed by then, and losing the write to save the catalogue is backwards.
async function regenerateIndexes(): Promise<void> {
  await regenerateBareIndex();
}

export async function writeNote(
  path: string,
  content: string,
  mode: "create" | "replace" | "append"
): Promise<{ path: string; commitSha: string; indexWarning?: string }> {
  validatePath(path);
  const existing = await getFile(path);
  if (mode === "create" && existing) {
    throw new Error(`${path} already exists — use replace or append.`);
  }
  if (mode === "replace" && !existing) {
    throw new Error(`${path} does not exist — use create.`);
  }
  const finalContent =
    mode === "append" ? joinAppend(existing?.content, content, content) : content;
  const { commitSha } = await putFile(
    path,
    finalContent,
    `brain: ${mode} ${path}`,
    existing?.sha,
    mode === "append" ? (fresh) => joinAppend(fresh?.content, content, content) : undefined
  );
  let indexWarning: string | undefined;
  try {
    await regenerateIndexes();
  } catch (e) {
    indexWarning = e instanceof Error ? e.message : String(e);
  }
  return { path, commitSha, indexWarning };
}


export async function capture(
  text: string,
  tags?: string[]
): Promise<{ path: string; commitSha: string; indexWarning?: string }> {
  const { date, time } = todayStamp();
  const path = `log/${date}.md`;
  const heading = tags && tags.length > 0 ? `## ${time} · ${tags.join(", ")}` : `## ${time}`;
  const entry = `${heading}\n\n${text}\n`;
  const existing = await getFile(path);
  const whenMissing = `# Log ${date}\n\n${entry}`;
  const finalContent = joinAppend(existing?.content, entry, whenMissing);
  const { commitSha } = await putFile(
    path,
    finalContent,
    `brain: capture ${date} ${time}`,
    existing?.sha,
    (fresh) => joinAppend(fresh?.content, entry, whenMissing)
  );
  let indexWarning: string | undefined;
  try {
    await regenerateIndexes();
  } catch (e) {
    indexWarning = e instanceof Error ? e.message : String(e);
  }
  return { path, commitSha, indexWarning };
}
