import { unescaped, type SourceHit } from "./export-scan";

export type PublicReference = { file: string; repository: string; workflow: string; ref: string };

const POLICY_FILE = "tests/helpers/export-public-references.json";
const WORKFLOW_PATH = /^\.github\/workflows\/[A-Za-z0-9_-]+\.ya?ml$/;

function validateReferences(references: readonly PublicReference[]): void {
  if (!Array.isArray(references)) throw new Error("Invalid public reference policy");
  const files = new Set<string>();
  for (const reference of references) {
    if (!reference || typeof reference !== "object"
      || Object.keys(reference).sort().join(",") !== "file,ref,repository,workflow"
      || !Object.values(reference).every((value) => typeof value === "string")
      || !WORKFLOW_PATH.test(reference.file) || !WORKFLOW_PATH.test(reference.workflow)
      || !/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(reference.repository)
      || !/^[A-Za-z0-9][A-Za-z0-9_./-]*$/.test(reference.ref)
      || files.has(reference.file)) throw new Error("Invalid public reference policy");
    files.add(reference.file);
  }
}

// Approve only repository-name spans, never the surrounding line or file. Exact
// forms deliberately fail closed when an installer changes its output.
function publicRepositorySpans(file: string, text: string, references: readonly PublicReference[]): Array<[number, number]> {
  const spans: Array<[number, number]> = [];
  const applicable = references.filter((reference) => reference.file === file || file === POLICY_FILE);
  if (!applicable.length) return spans;
  let offset = 0;
  for (const line of text.split("\n")) {
    const trimmed = line.trim();
    for (const { repository, workflow, ref } of applicable) {
      const declaration = `"repository": ${JSON.stringify(repository)}`;
      const approved = file === POLICY_FILE
        ? trimmed === declaration || trimmed === `${declaration},`
        : trimmed === `# Installed by ${repository}. Do not edit this file by hand - it is`
          || trimmed === `# Full description: https://github.com/${repository}`
          || trimmed === `uses: ${repository}/${workflow}@${ref}`;
      if (approved) {
        const start = offset + line.indexOf(repository);
        spans.push([start, start + repository.length]);
      }
    }
    offset += line.length + 1;
  }
  return spans;
}

export function noteNameHits(sources: Array<[string, string]>, stems: Iterable<string>, references: readonly PublicReference[]): SourceHit[] {
  validateReferences(references);
  const names = [...new Set(stems)].filter(Boolean);
  const hits: SourceHit[] = [];
  const reported = new Set<string>();
  for (const [file, raw] of sources) {
    // Decode separately: replacing approved text would hide leaks from other
    // gates, and reusing offsets after decoding could approve the wrong bytes.
    for (const text of new Set([raw, unescaped(raw)])) {
      const spans = publicRepositorySpans(file, text, references);
      for (const stem of names) {
        const key = JSON.stringify([file, stem]);
        if (reported.has(key)) continue;
        let at = text.indexOf(stem);
        while (at >= 0 && spans.some(([start, end]) => at >= start && at + stem.length <= end)) {
          at = text.indexOf(stem, at + 1);
        }
        if (at < 0) continue;
        hits.push({ file, line: text.slice(0, at).split("\n").length, origin: stem });
        reported.add(key);
      }
    }
  }
  return hits;
}
